### ISSUE TITLE
Small setup fix

### ISSUE THREAD

**Issue by zlefler** [learn-co-curriculum/phase-0-wsl2-env-verification#4]
### Canvas Link

https://learning.flatironschool.com/courses/4976/pages/verify-and-troubleshoot-your-wsl2-environment-setup?module_item_id=345635

### Concern

In this section you have us make sure that the Ruby version is 2.7.4, but in a previous setup section you have us set 2.6.1 as default. Not a big thing, but might as well make the first one right.

### Additional Context

https://learning.flatironschool.com/courses/4976/pages/windows-wsl2-ruby-installation?module_item_id=345633

That's the page where it says to install an earlier version

**Comment by graciemcguire** [comment]
Hello @Leavingvalhalla , and thank you for spotting this issue and providing feedback!

We have updated the GitHub repo and believe your issue to have been resolved. 
Note, however, that if you are working in Canvas the changes may not show up 
there, but they will for future students.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not!
We appreciate your support! 💙
